### ISSUE TITLE
Perform any extra steps before deleting model

### ISSUE THREAD

**Issue by sajaddp** [LaravelDaily/laravel-tips#104]
Hi,
Is this correct?

https://github.com/LaravelDaily/laravel-tips/blob/3240a00da226b833e14af18c9a97fbd0cd691ac2/DB_Models_and_Eloquent.md?plain=1#L749

This function is not static in the parent class. [reference](https://github.com/laravel/framework/blob/0fbbbf2ac4d3e3bb9205313388d35e86a496eef4/src/Illuminate/Database/Eloquent/Model.php#L1330)

**Comment by PovilasKorop** [comment]
@sajaddp thanks for reporting, I've removed that tip
