### ISSUE TITLE
Pivot Table with Extra Relations (https://github.com/LaravelDaily/laravel-tips#pivot-table-with-extra-relations)

### ISSUE THREAD

**Issue by AbirkulovSherali** [LaravelDaily/laravel-tips#12]
Thank you for such usefull information. It would be nice if you add advice that tells how to eager load relations on a pivot table to avoid "n + 1 queries" problem. There's a usefull package which resolve this problem . See for more information - [https://github.com/ajcastro/eager-load-pivot-relations](https://github.com/ajcastro/eager-load-pivot-relations)

**Comment by PovilasKorop** [comment]
@AbirkulovSherali it's quite a rare case, in my opinion. In this repository, I accept Pull Request with Laravel Tips, if you write it, but this wouldn't be on my list of very useful tips.

**Comment by AbirkulovSherali** [comment]
@PovilasKorop but still, the case in "Pivot Table with Extra Relations" section is a quite rare case itself. If there is a section how to add an extra relation, then there should be a section describing how to eager load (of course if there is ability to do that). Thank you.

**Comment by PovilasKorop** [comment]
@AbirkulovSherali I guess you're right, but it's not something I would personally add. If you want to add it, please submit a Pull Request and I may accept it.

**Comment by AbirkulovSherali** [comment]
Ok.

**Comment by AbirkulovSherali** [comment]
@PovilasKorop ok.
