### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ThaysonScript** [LaravelDaily/laravel-tips#132]
Would you like to have a version translated into Portuguese?

**Comment by PovilasKorop** [comment]
@ThaysonScript I don't have any goals for translations, just some people did it themselves without me asking them :)

**Comment by ThaysonScript** [comment]
I would also like to contribute with some tips on laravel 10, but for now the translation is easier :)

**Comment by ThaysonScript** [comment]
I understand lol :)

**Comment by ThaysonScript** [comment]
this would bring more depth to the repository and organization

**Comment by ThaysonScript** [comment]
> @ThaysonScript feel free to do that, sure, if you think it would help the Brazilian audience.
> 
> Although, I would prefer people learning English as international language, would be more beneficial for them if they want to have international career :)

I'm still learning English, so it will be a good language exercise too

**Comment by PovilasKorop** [comment]
@ThaysonScript nah I wouldn't accept it into the main repository cause then I become responsible for future translations for future tips.

But you can fork the repository into your own one, like others did.

**Comment by ThaysonScript** [comment]
yeah, sure, I hadn't stopped to think about it, but ok I'll be doing what I recommend :)
