### ISSUE TITLE
Duplicated tips

### ISSUE THREAD

**Issue by lucasjose501** [LaravelDaily/laravel-tips#94]
I was reading the tips before and found what I think is a duplication of the same subject.

Not sure if this is intended, but seems like it could be merged into one:

Both are about the data_get function

https://github.com/LaravelDaily/laravel-tips/blob/master/Other.md#data-get-function
https://github.com/LaravelDaily/laravel-tips/blob/master/Other.md#dealing-with-deeply-nested-arrays

Thank you.

**Comment by PovilasKorop** [comment]
@lucasjose501 good catch, just written by different people who didn't check each other's example.

I'm extremely busy this Summer, but if you have time, you can submit a Pull Request for the merge. Thanks!
