### ISSUE TITLE
Http concurrent calls tip idea

### ISSUE THREAD

**Issue by henzeb** [LaravelDaily/laravel-tips#99]
I am not talking about Http::pool(). This just does all given calls at once. I am talking about crawler situations where you are crawling 100s of urls and want a concurrency of 10 requests at a time without creating a new Pool every time 10 are done.
You could use the following text I wrote as an answer for a question at Laravel's github discussions page. See:
https://github.com/laravel/framework/discussions/43063#discussioncomment-3521639

**Comment by PovilasKorop** [comment]
@henzeb great suggestion, but I wouldn't classify that as a "quick tip" for this repository, to me it looks more like a blog post, describing the problem and the solution with code fragment.

If you ever publish a blog, send me the link, and I will gladly share it on my social feed.

**Comment by henzeb** [comment]
You don't have to use it all, just the first part with the Each::forLimit inside the Http::pool call...

**Comment by PovilasKorop** [comment]
@henzeb then can you make a Pull Request, please?
